---

- name: Install ROS stack on Raspbian lite
  hosts: ros
  remote_user: pi
  roles:
    - role: raspbian
      vars:
        config_arm_freq: 1600
        config_over_voltage: 4
    - role: ros
    # uncommect when reboot issue is resolved
    # - role: workspace