---

- name: Install ROS stack on Raspbian lite
  hosts: ros
  remote_user: pi
  roles:
    - role: raspbian
      vars:
        config_arm_freq: 1600
        config_over_voltage: 4
        can_overclock: false
    - role: ros-node
    - role: workspace