---

- name: Install ROS stack on Raspbian lite
  hosts: ros
  remote_user: pi
  roles:
    - role: raspbian
      vars:
        can_overclock: false
    - role: ros-node
      vars:
        workdir: /home/pi/workdir
    - role: workspace