---

- name: Add identity key to authorized keys on host
  authorized_key: 
    user: pi
    key: "{{ lookup('file', ssh_identity_key) }}"
  register: add_identity_key
  when: ssh_identity_key is defined

- name: Disable password and host based authentication
  become: true
  lineinfile: 
    dest: /etc/ssh/ssh_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^#?\s*PasswordAuthentication ', line: 'PasswordAuthentication no' }
    - { regexp: '^#?\s*?HostbasedAuthentication ', line: 'HostbasedAuthentication no' }
    - { regexp: '^#?\s*?ChallengeResponseAuthentication ', line: 'ChallengeResponseAuthentication no' }
    - { regexp: '^#?\s*?UsePAM ', line: 'UsePAM no' }
  when: add_identity_key is success and not add_identity_key is skipped
  notify: restart sshd

- name: lock pi user's password
  become: true
  user:
    name: pi
    password_lock: yes
  when: add_identity_key is success and not add_identity_key is skipped

- name: Update all packages to the latest version
  become: true
  apt:
    upgrade: dist
    update_cache: yes

- name: Remove useless packages from the cache
  become: true
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: Set overclock settings
  become: true
  lineinfile: 
    dest: /boot/config.txt
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: 'arm_freq', line: "arm_freq={{ config_arm_freq }}" }
    - { regexp: 'core_freq', line: "core_freq={{ config_core_freq }}" }
    - { regexp: 'sdram_freq', line: "sdram_freq={{ config_sdram_freq }}" }
    - { regexp: 'over_voltage', line: "over_voltage={{ config_over_voltage }}" }
  when: can_overclock
  register: overclock

- name: Increase swapsize
  become: true
  lineinfile: 
    dest: /etc/dphys-swapfile
    regexp: 'CONF_SWAPSIZE='
    line: 'CONF_SWAPSIZE=1024'
  register: swapsize

- name: Reboot immediately if there was a change.
  become: true
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: overclock.changed or swapsize.changed

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: overclock.changed or swapsize.changed
